### ISSUE TITLE
ToopherIframe.validate mutates the data parameter, which might be immutable

### ISSUE THREAD

**Issue by smholloway** [toopher/toopher-python#29]
In Flask, the request data is an `ImmutableMultiDict`, so the `ToopherIframe.validate` method will throw an error when trying to delete the Toopher signature. 

Here's how [I called `validate`](https://github.com/smholloway/toopher-iframe-example-in-python/blob/master/app.py#L45):

```
validated_data = api.validate(request.args, request_token)
```

And this is the [line that threw the error](https://github.com/toopher/toopher-python/blob/develop/toopher/__init__.py#L84): 

```
del data['toopher_sig']
```

I suggest we make a mutable copy of the `data` that we can manipulate and return. There's probably a cleaner way to do it, but this is how I got around it in [my example](https://github.com/smholloway/toopher-iframe-example-in-python/blob/master/app.py#L21-L25):

```
mutable_dict = {}
for key in data.keys():
    mutable_dict[key] = data[key]
```

**Comment by egrim** [comment]
Nice catch, @smholloway - note that we'll need to decide whether we want a shallow copy:

```
mutable_dict = dict(data)
```

or a deepcopy:

```
import copy
mutable_dict = copy.deepcopy(data)
```

**Comment by smholloway** [comment]
See PR #30

**Comment by trdarr** [comment]
#30 addressed this issue and was merged six months ago.
